version: '3.8'

services:
  app:
    build:
      context: .
    restart: always
    ports:
    - "127.0.0.1:3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
